services:
  mambacd:
    image: building_cd:latest
    volumes:
      - ./workspace:/workspace
    shm_size: '50gb'
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1
      - FORCE_COLOR=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: sh -c "python /workspace/predict.py --dataset_path ${dataset_path} --output_path ${output_path} --model_path ${model_path}"
