version: '3.9'

services:
  mambacd:
    image: building_cd:latest
    volumes:
      - ./workspace:/workspace
      # - [host]:[container]
      # build:
      #   dockerfile: ./dockerfile
      #   shm_size: '30gb'
    shm_size: '30gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    command: sh -c "python /workspace/predict.py --dataset_path ${dataset_path} --output_path ${output_path} --model_path ${model_path}"
